# To build, run this from the root directory of the repo:

# sudo docker build -t projectastro.azurecr.io/pb4 -f dockerfiles/pb1/dockerfile . --no-cache
# sudo az acr login --name projectastro
# sudo docker push projectastro.azurecr.io/pb4
#
# To run locally:

# sudo az acr login --name projectastro
# sudo docker pull projectastro.azurecr.io/pb4:latest
# sudo docker run -it projectastro.azurecr.io/pb4:latest bash

FROM continuumio/miniconda3
WORKDIR /opt/pb

RUN conda update -n base -c defaults conda

ADD "pb-human-wgs-workflow-snakemake/scripts" /opt/pb/scripts
ADD "pb-human-wgs-workflow-snakemake/rules/envs" /opt/pb/envs
ADD "dockerfiles/pb1/create_conda_envs.sh" /opt/pb/setup/create_conda_envs.sh

WORKDIR /opt/pb/setup
RUN chmod +x create_conda_envs.sh
RUN ./create_conda_envs.sh
