# jellyfish and genomescope
kmer_length: 21

# deepvariant
#DEEPVARIANT_VERSION: "1.0.0"  # CPU-only, will require modifying threads for call_variants rules
DEEPVARIANT_VERSION: "1.0.0-gpu"  # GPU
N_SHARDS: 256

# glnexus
GLNEXUS_VERSION: "v1.2.7"

# gfatools
GFATOOLS_VERSION: "0.4"

# slivar
slivar_js: "resources/slivar/slivar-functions.js"

# lookups for slivar tsv annotations
lof_lookup_url: "https://storage.googleapis.com/gnomad-public/release/2.1.1/constraint/gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz"
lof_lookup: "resources/slivar/lof_lookup.txt"
clinvar_lookup_url: "ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/gene_condition_source_id"
clinvar_lookup: "resources/slivar/clinvar_gene_desc.txt"

# cohorts yaml
cohort_yaml: "cohort.yaml"

# lookups for gene mapping
ensembl_to_hgnc: 'resources/hpo/ensembl.hgncSymbol.tsv'

# lookups for HPO annotations
hpo:
  terms: 'resources/hpo/hpoTerms.txt'
  dag: 'resources/hpo/hpoDag.txt'
  annotations: 'resources/hpo/ensembl.hpoPhenotype.tsv'
